name = "Millipede bar experimental parameters"

[material_properties]
elastic_modulus = 200e9  # Young's modulus (Pa)
density = 7850  # (kg/m3)

[geometric_parameters]
junction_length = 4e-3  # (m)
gage_distance = 50e-3  # Distance from the strain gage to the junction (m)